from models.finance_models import TipoTransacao

USUARIOS = [
    (1, "Arthur", 5537.70),
    (2, "Yasmin", 1800.00),
]

REGISTROS_FINANCEIROS = [
    {
        "id": 1,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Internet",
        "valor_por_parcela": 80.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 2,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Energia",
        "valor_por_parcela": 30.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 3,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Água",
        "valor_por_parcela": 80.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 4,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Streaming",
        "valor_por_parcela": 44.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 5,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Bloqueador",
        "valor_por_parcela": 10.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 6,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Spotify-Arthur",
        "valor_por_parcela": 12.90,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 7,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 2,
        "nome": "Spotify-Yasmin",
        "valor_por_parcela": 12.90,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 8,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Academia",
        "valor_por_parcela": 90.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 9,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Feira",
        "valor_por_parcela": 340.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 10,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 2,
        "nome": "Geladeira",
        "valor_por_parcela": round(1049.93 / 6, 2),
        "valor_total": 1049.93,
        "parcelas_restantes": 6,
    },
    {
        "id": 11,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 1,
        "nome": "Cadeira",
        "valor_por_parcela": round(683.14 / 1, 2),
        "valor_total": 683.14,
        "parcelas_restantes": 1,
    },
    {
        "id": 12,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 1,
        "nome": "Cerâmica",
        "valor_por_parcela": round(2199.96 / 4, 2),
        "valor_total": 2199.96,
        "parcelas_restantes": 4,
    },
]
