from models.finance_models import TipoTransacao

USUARIOS = [
    (1, "Lucas", 4200.50),
    (2, "Mariana", 3100.00),
    (3, "Pedro", 2750.90),
    (4, "Aline", 1980.30),
    (5, "Ricardo", 5120.70),
]

REGISTROS_FINANCEIROS = [
    # CONTAS FIXAS
    {
        "id": 1,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Internet Fibra",
        "valor_por_parcela": 120.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 2,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 1,
        "nome": "Plano Celular",
        "valor_por_parcela": 49.90,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 3,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 2,
        "nome": "Água",
        "valor_por_parcela": 68.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 4,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 3,
        "nome": "Energia",
        "valor_por_parcela": 142.50,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    # ASSINATURAS / SERVIÇOS
    {
        "id": 5,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 4,
        "nome": "Netflix",
        "valor_por_parcela": 55.90,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 6,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 5,
        "nome": "Spotify",
        "valor_por_parcela": 21.90,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    # GASTOS MENSAIS
    {
        "id": 7,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 2,
        "nome": "Supermercado",
        "valor_por_parcela": 320.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    {
        "id": 8,
        "tipo": TipoTransacao.CONTA,
        "usuario_id": 3,
        "nome": "Transporte",
        "valor_por_parcela": 150.00,
        "valor_total": None,
        "parcelas_restantes": None,
    },
    # DÍVIDAS PARCELADAS
    {
        "id": 9,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 1,
        "nome": "Notebook",
        "valor_por_parcela": round(3540.00 / 10, 2),
        "valor_total": 3540.00,
        "parcelas_restantes": 10,
    },
    {
        "id": 10,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 2,
        "nome": "Smartphone",
        "valor_por_parcela": round(2299.90 / 12, 2),
        "valor_total": 2299.90,
        "parcelas_restantes": 12,
    },
    {
        "id": 11,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 4,
        "nome": "Cama Box",
        "valor_por_parcela": round(980.00 / 5, 2),
        "valor_total": 980.00,
        "parcelas_restantes": 5,
    },
    {
        "id": 12,
        "tipo": TipoTransacao.DIVIDA,
        "usuario_id": 5,
        "nome": "Curso Online",
        "valor_por_parcela": round(600.00 / 3, 2),
        "valor_total": 600.00,
        "parcelas_restantes": 3,
    },
]
